//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI5sWeb.Modules.Contabilidad.PresupuestoGastos {
    
    
    public partial class CapturaPresupuesto {
        
        /// <summary>
        /// desccentro control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label desccentro;
        
        /// <summary>
        /// PreviousPage property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new NI5Web.Modules.Contabilidad.presupuestacion PreviousPage {
            get {
                return ((NI5Web.Modules.Contabilidad.presupuestacion)(base.PreviousPage));
            }
        }
    }
}
